### Test home page
GET http://localhost:8000/
Accept: application/json

###

### Test successful login
POST http://localhost:8000/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=password

###

### Test failed login (wrong password)
POST http://localhost:8000/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=wrong

###

### Test failed login (unknown user)
POST http://localhost:8000/login
Content-Type: application/x-www-form-urlencoded

username=intruder&password=hacker

